### ISSUE TITLE
Updated XRCE-DDS library

### ISSUE THREAD

**Issue by tieugiang91** [AmarNathH/Micro-XRCE-DDS-Client-ESP8266#1]
The library's API seems to be updated. The discovery function doesn't work. May you kindly instruct to way to update this library please?

**Comment by AmarNathH** [comment]
Yes the discovery feature has some issues. Also, I am not actively developing the project. Make sure you use Micro XRCE v1.1.0 with this library (the files are included in the repository already). If you want to upgrade it and put a pull request I will be happy to help :).

**Comment by AmarNathH** [comment]
Closed as there were no replies for a long long time.
